apiVersion: apps/v1
kind: Deployment
metadata:
  name: pidev-backend
  namespace: pidev
  labels:
    app: pidev-backend
    type: backend
spec:
  selector:
    matchLabels:
      app: pidev-backend
      type: backend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pidev-backend
        type: backend
    spec:
      containers:
      - name: pidev-backend
        image: ayoubmahou/pidev-back:1.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 768Mi
        env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: pidev-backend-secret
                key: MYSQL_HOST
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: pidev-backend-secret
                key: MYSQL_DB
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pidev-backend-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_ARGS
            valueFrom:
              secretKeyRef:
                name: pidev-backend-secret
                key: MYSQL_ARGS
        volumeMounts:
          - name: pidev-backend-volume
            mountPath: /config/application.yaml
            subPath: application.yaml
        ports:
        - containerPort:  8083
          name: tcp
      volumes:
        - name: pidev-backend-volume
          configMap:
            name: pidev-backend-config
            items:
              - key: application.yaml
                path: application.yaml
      restartPolicy: Always
