apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pidev-backend-pvc
  namespace: pidev
  labels:
    app: pidev-backend
    type: pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi