apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pidev-backend-db-secret
  namespace: pidev
  labels:
    app: pidev-backend
    type: secret
data:
  MYSQL_DB: UGlkZXY=
  MYSQL_ROOT_PASSWORD: cGlkZXYtYmFja2VuZA==