apiVersion: v1
kind: Service
metadata:
  name: pidev-backend-db-svc
  namespace: pidev
  labels:
    app: pidev-backend
    type: service
spec:
  clusterIP: None
  selector:
    app: pidev-backend-db
    type: db
  ports:
    - name: tcp
      protocol: TCP
      port: 3306